config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    passwords: 'users/passwords'
  }
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
    post 'users/guest_admin_sign_in', to: 'users/sessions#guest_admin_sign_in'
  end
  resources :users, only: [:show]
  resources :questions do
    resources :answers, only: [:new, :create, :edit, :destroy, :update]
  end
  resources :answer_words, only: [:update]
  root 'tops#top'
  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end
  get 'search', to: 'reminiscent_words_dictionaries#search'
  get 'result', to: 'questions#result'
  post 'questions/:id/answers/new', to: 'answers#create'
end

app/models/question.rb
class Question < ApplicationRecord
  validates :content, presence: true, length: { maximum: 1000 }
  has_many :answers, dependent: :destroy
  belongs_to :user
  has_many :reminiscent_words, dependent: :destroy
  accepts_nested_attributes_for :reminiscent_words, allow_destroy: true, reject_if: :all_blank
  enum status: {回答受付中:0, 解決済:1}
  scope :search_status, -> (status) { where(status: status)}
  has_many :reminiscent_words_dictionaries

  def answered_by?(user)
    answers.where(user: user).exists?
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :set_question, only: %i[show edit update destroy]
  before_action :authenticate_user!
  def index
    @questions = Question.all.order(created_at: :desc)
    if params[:search_status].present?
      @questions = Question.search_status(params[:search_status])
    end
  end

  def show
    @answer_word = AnswerWord.new
  end

  def new
    @question = Question.new
    @reminiscent_words = @question.reminiscent_words.build
  end

  def edit
    if current_user != @question.user
      redirect_to questions_path, alert: '他のユーザーの質問投稿は編集できません'
    end
  end

  def create
    @question = current_user.questions.build(question_params)
    if params[:back]
      render :new
    else
      respond_to do |format|
        if @question.save
          format.html { redirect_to @question, notice: "質問を投稿しました" }
          format.json { render :show, status: :created, location: @question }
        else
          format.html { render :new, status: :unprocessable_entity }
          format.json { render json: @question.errors, status: :unprocessable_entity }
        end
      end
    end
  end

  def update
    respond_to do |format|
      # 解決済の質問の場合は更新させない
      if @question.status == 1
        redirect_to @question, alert: '解決済みの質問は編集できません。'
      elsif @question.update(question_params)
        format.html { redirect_to @question, notice: "質問投稿を編集しました" }
        format.json { render :show, status: :ok, location: @question }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    # 解決済の質問の場合は削除させない
    if @question.status == 1
      redirect_to @question, alert: '解決済みの質問は削除できません。'
    else
      @question.destroy
      respond_to do |format|
        format.html { redirect_to questions_url, notice: "質問投稿を削除しました" }
        format.json { head :no_content }
      end
    end
  end

  private
  def set_question
    @question = Question.find(params[:id])
  end

  def question_params
    params.require(:question).permit(:content, :sentence, :status, reminiscent_words_attributes: [:id, :keyword, :_destroy])
  end
end

app/helpers/questions_helper.rb
module QuestionsHelper
  def button_text
    if action_name == "new"
      "質問を投稿する"
    elsif action_name == "edit"
      "変更する"
    end
  end
end

app/views/questions/_form.html.erb
<%= form_with(model: question, local: true) do |form| %>
  <% if question.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(question.errors.count, "件の") %>エラーがあります。</h2>
      <ul>
      <% question.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field question-content">
    <div><%= form.label "質問内容" %></div>
    <div><%= form.text_area :content, size: "60x10" %></div>
  </div>

  <div class="field question-content">
    <div><%= form.label "前後の文脈" %></div>
    <div><%= form.text_area :sentence, size: "60x10" %></div>
  </div>

  <div class="field">
    <%= form.fields_for :reminiscent_words do |w| %>
      <%= render "reminiscent_word_fields", f: w %>
    <% end %>
    <div class="links">
        <button><%= link_to_add_association "連想ワードを追加", form, :reminiscent_words %></button>
    </div>
  </div>

  <div class="actions">
    <%= form.submit button_text %>
  </div>
<% end %>

app/views/questions/_reminiscent_word_fields.html.erb
<div class="nested-fields">
  <%= f.hidden_field :id %>
  <div><%= f.label "連想ワード", {class: 'reminiscent-word'} %></div>
  <%= f.text_field :keyword %>
  <button><%= link_to_remove_association "削除", f %></button>
</div>

app/views/questions/edit.html.erb
<head>
  <%= stylesheet_link_tag 'questions/edit', :media => "all" %>
</head>

<div class="main-content">
  <h1>質問編集</h1>
  <%= render 'form', question: @question %>
  <div class="show_click">
    <button><%= link_to '戻る', @question %></button>
  </div>
</div>

app/views/questions/index.html.erb
<head>
  <%= stylesheet_link_tag 'questions/index', :media => "all" %>
</head>
<div class="main_content">
  <h1>質問一覧</h1>
  <div class="input-group">
    <%= form_with model: @question, method: :get, local: true do |form| %>
      <div class="status_select">
        <%= form.select :search_status, Question.statuses.keys, {}, { class: 'status_select' } %>
      </div>
      <div class="status_select_item">
        <button class="button"><%= form.submit '絞り込み', name: 'search' %></button>
        <button class="button"><%= link_to '解除', questions_path %></button>
      </div>
    <% end %>
  </div>
  <div class="questions_list">
    <% @questions.each do |question| %>
      <div class="question_row">
        <div class="status_area">
          <label class="<%= question.status == "回答受付中" ? 'open ': 'close ' %>status_label"><%= question.status %></label>
        </div>
        <div class="middle_area">
          <div class="question_content">
            <p><%= question.content %></p>
          </div>
          <p class="reminiscent_word_title">連想ワード</p>
          <div class="reminiscent_words_area">
            <% question.reminiscent_words.each do |reminiscent_word| %>
              <label class="reminiscent_word_label">
                <%= reminiscent_word.keyword %>
              </label>
            <% end %>
          </div>
        </div>
        <div class="detail_link_area">
          <% if question.user == current_user || question.status == "解決済" %>
            <button class="button"><%= link_to '詳細', question %></button>
          <% else %>
            <button class="button"><%= link_to '回答する', new_question_answer_path(question) %></button>
          <% end %>
        </div>
        <div class="question_info_area">
          <p><%= "投稿日時 : " + question.created_at.strftime('%Y/%m/%d') %></p>
          <p><%= question.user.name %></p>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/questions/new.html.erb
<%= stylesheet_link_tag 'questions/new', :media => "all" %>

<div class="main-content">
  <h1>質問を投稿する</h1>

  <%= render 'form', question: @question %>
</div>

app/views/questions/show.html.erb
<head>
  <%= stylesheet_link_tag 'questions/show', :media => "all" %>
</head>
<div class="main_content">
  <h1><%= @question.status %></h1>
  <div class="question">
    <div class="question-main">
      <div class="content">
        <label>質問内容</label>
        <p><%= @question.content %></p>
      </div>
      <div class="sentence">
        <label>前後の文脈</label>
        <p><%= @question.sentence %></p>
      </div>
    </div>
    <div class="question-sub">
      <div class="reminiscent-word">
        <% @question.reminiscent_words.each do |reminiscent_word| %>
          <label><%= reminiscent_word.keyword %></label>
        <% end %>
      </div>
      <div class="button-area">
        <% if @question.user_id == current_user.id && @question.status != "解決済" %>
          <button><%= link_to '変更する', edit_question_path(@question) %></button>
          <button><%= link_to '削除する', @question, method: :delete, data: { confirm: '本当に削除しますか?' } %></button>
        <% end %>
      </div>
    </div>
  </div>
  <div class="answer-area">
    <h2>回答一覧</h2>
    <div class="divider"></div>
    <div id="answers">
      <!-- 投稿されたコメント一覧をブログの詳細ページに表示するためのrender -->
      <%= render partial: 'answers/index', locals: { answers: @question.answers, question: @question, answer_word: @answer_word } %>
    </div>
  </div>
</div>