config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    passwords: 'users/passwords'
  }
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
    post 'users/guest_admin_sign_in', to: 'users/sessions#guest_admin_sign_in'
  end
  resources :users, only: [:show]
  resources :questions do
    resources :answers, only: [:new, :create, :edit, :destroy, :update]
  end
  resources :answer_words, only: [:update]
  root 'tops#top'
  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end
  get 'search', to: 'reminiscent_words_dictionaries#search'
  get 'result', to: 'questions#result'
  post 'questions/:id/answers/new', to: 'answers#create'
end

app/models/reminiscent_words_dictionary.rb
class ReminiscentWordsDictionary < ApplicationRecord
  validates :answer_word, presence: true, length: { maximum:50 }
  validates :reminiscent_word, presence: true, length: { maximum:50 }
  belongs_to :question
end

app/controllers/reminiscent_words_dictionaries_controller.rb
class ReminiscentWordsDictionariesController < ApplicationController
  before_action :authenticate_user!, only: [:search]
  def search
    @q = ReminiscentWordsDictionary.ransack(params[:q])
    @reminiscent_words_dictionaries = ReminiscentWordsDictionary.all
    if params[:q]
      @search_word = params[:q]
      @results = @q.result
    end
  end

  # def search
  #   @reminiscent_words_dictionaries = ReminiscentWordsDictionary.all
  #   @q = ReminiscentWordsDictionary.ransack(params[:q])
  #   if params[:q]
  #     @search_word = params[:q]
  #     @results = []
  #     @results_colllection = []
  #     @search_words = params[:q]['reminiscent_word_matches_all'].split(/[ |　]/)
  #     @search_words_formatted = @search_words.map {|v| "%#{v}%"}
  #     @search_words_formatted.each do |swf|
  #       @search_words_hash = {}
  #       @search_words_hash['reminiscent_word_matches_all'] = swf
  #       @results_by_single_search_word = ReminiscentWordsDictionary.ransack(@search_words_hash).result
  #       @results_colllection.push(@results_by_single_search_word)
  #     end
  #     @results_answer_words = []
  #     @results_colllection.length.times do
  #       @tmp_rwd_array = @results_colllection.shift
  #       @tmp_rwd_array.each do |tmp_i_rwd|
  #         if @results_colllection[0].any? { |tmp_j_rwd| tmp_j_rwd.answer_word == tmp_i_rwd.answer_word }
  #           if results_answer_words.all? { |raw| raw != tmp_i_rwd.answer_word }
  #             @results.push(mp_i_rwd)
  #             @results_answer_words.push(tmp_i_rwd.answer_word)
  #           end
  #         end
  #       end
  #     end
  #   end
  # end
end

app/helpers/reminiscent_words_dictionaries_helper.rb
module ReminiscentWordsDictionariesHelper
end

app/helpers/reminiscent_words_dictionary_helper.rb
module ReminiscentWordsDictionariesHelper
end

app/views/reminiscent_words_dictionaries/search.html.erb
<head>
  <%= stylesheet_link_tag 'search', :media => "all" %>
</head>
<div class="main_content">
  <div class="top_content">
    <h1>連想ワードで検索する</h1>
    <h3>あなたが表現したいイメージから連想できる単語や文章を入力してしっくりくる言葉を探してみよう。</h3>
    <p>(※解決済になった質問投稿に対する連想ワードのみ検索ができます。)</p>
    <h4>"ヒント"　イメージに近い単語（類語）、イメージの特徴</h4>
    <%= search_form_for @q, url: search_path do |f| %>
      <%= search_field_tag "q[reminiscent_word_matches_all]" %>
      <br>
      <div class="text_align_right">
        <button><%= f.submit '検索' %></button>
      </div>
    <% end %>
  </div>

  <% if @search_word.present? %>
    <h3>しっくりくる言葉は見つかりましたか？</h3>
    <div class="results_list">
      <% @results.each do |r| %>
        <div class="answer_word">
          <p><%= r.answer_word %></p>
          <button><%= link_to "質問投稿の詳細", question_path(r.question_id) %></button>
        </div>
      <% end %>
    </div>
  <% end %>
</div>