config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    passwords: 'users/passwords'
  }
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
    post 'users/guest_admin_sign_in', to: 'users/sessions#guest_admin_sign_in'
  end
  resources :users, only: [:show]
  resources :questions do
    resources :answers, only: [:new, :create, :edit, :destroy, :update]
  end
  resources :answer_words, only: [:update]
  root 'tops#top'
  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end
  get 'search', to: 'reminiscent_words_dictionaries#search'
  get 'result', to: 'questions#result'
  post 'questions/:id/answers/new', to: 'answers#create'
end

app/models/answer.rb
class Answer < ApplicationRecord
  validates :comment, length: { maximum: 1000 }
  belongs_to :question
  validates :comment, presence: true
  belongs_to :user
  has_many :answer_words, dependent: :destroy
  accepts_nested_attributes_for :answer_words, reject_if: :all_blank, allow_destroy: true
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  before_action :set_question, only: [:new, :create, :edit, :update]
  def new
    @answers = @question.answers
    @answer = @question.answers.build
    @answer_words = @answer.answer_words.build
  end

  def create
    @answer = @question.answers.build(answer_params)
    @answer.user_id = current_user.id
    respond_to do |format|
      if @answer.save
        @answer = @question.answers.build
        format.js { render :index }
      else
        format.html { redirect_to new_question_answer_path(@question), notice: '回答できませんでした...' }
      end
    end
  end

  def edit
    @answer = @question.answers.find(params[:id])
    @answer_words = @answer.answer_words
    respond_to do |format|
      flash.now[:notice] = 'コメントの編集中'
      format.js { render :edit }
    end
  end
  def update
    @answer = @question.answers.find(params[:id])
      respond_to do |format|
        if @answer.update(answer_params)
          flash.now[:notice] = 'コメントが編集されました'
          format.js { render :index }
        else
          flash.now[:notice] = 'コメントの編集に失敗しました'
          format.js { render :edit_error }
        end
      end
  end
  def destroy
    @answer = Answer.find(params[:id])
    @answer.destroy
    respond_to do |format|
      flash.now[:notice] = 'コメントが削除されました'
      format.js { render :index }
    end
  end
  private
  def set_question
    @question = Question.find(params[:question_id])
  end

  def answer_params
    params.require(:answer).permit(:question_id, :comment, answer_words_attributes: [:id, :candidate, :_destroy])
  end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/views/answers/_answer_word_fields.html.erb
<div class="nested-fields">
  <%= f.text_field :candidate %>
  <button><%= link_to_remove_association "削除", f %></button>
</div>

app/views/answers/_edit.html.erb
<%= form_with(model: [question, answer]) do |form| %>
  <% if answer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(answer.errors.count, "error") %> prohibited this answer from being saved:</h2>
      <ul>
      <% answer.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= form.label "しっくりくる言葉候補", {class: 'answer-word'} %>
    <%= form.fields_for :answer_words do |aw|%>
        <%= render "answer_word_fields", f: aw %>
    <% end %>
    <div class="links">
      <%# link_to_add_association "しっくりくる言葉を追加", form, :answer_words %>
      <button><%= link_to_add_association "しっくりくる言葉を追加", form, :answer_words %></button>
    </div>
  </div>
  <div class="field">
    <div class="answer_comment">
      <%= form.label :comment %>
    </div>
    <%= form.text_area :comment, id: "answer_comment_#{question.id}", class: "edit-comment" %>

  </div>
  <div class="actions">
    <%= form.submit '回答を編集する' %>
  </div>
<% end %>

app/views/answers/_form.html.erb
<%= form_with(model: [question, answer], class: "new_answer_form") do |form| %>
  <% if answer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(answer.errors.count, "error") %> prohibited this answer from being saved:</h2>
      <ul>
      <% answer.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= form.label "しっくりくる言葉候補", {class: 'answer-word'} %>
    <%= form.fields_for :answer_words do |aw|%>
        <%= render "answer_word_fields", f: aw %>
    <% end %>
    <div class="links">
      <button><%= link_to_add_association "しっくりくる言葉を追加", form, :answer_words %></button>
    </div>
    <div class="answer_comment">
      <%= form.label :comment %>
    </div>
    <%= form.text_area :comment, size: "50x4" %>
    <div class="actions">
      <%= form.submit '回答する' %>
    </div>
  </div>
<% end %>

app/views/answers/_index.html.erb
<% answers.each do |answer| %>
  <% if answer.id.present? %>
    <div class="answer-comment" id ="this_answer_<%= answer.id %>">
      <div class="answer_index">
        <% if answer.answer_words.present? %>
          <label>しっくりくる言葉候補</label>
        <% end %>
        <div class="background_candidate_area">
          <% answer.answer_words.each do |answer_word| %>
            <div class="candidate_area">
              <div class="candidate">
                <label><%= answer_word.candidate %></label>
              </div>
              <div class="best-answer-label" >
                <% if current_user == @question.user && @question.status != "解決済" %>
                  <%= form_with( model: answer_word, local: true, url: answer_word_path, class: "best_answer_form") do |ba| %>
                    <%= ba.hidden_field :id, :value => answer_word.id %>
                    <%= ba.submit 'ベストアンサーにする', class: "best_answer_button" %>
                  <% end %>
                <% end %>
                <% if answer_word.best_answer_flg == true && @question.status == "解決済" %>
                  <label id="best_answer">ベストアンサー</label>
                <% end %>
              </div>
            </div>
          <% end %>
        </div>
        <div class="comment-area" >
          <% if answer.comment.present? %>
            <label>コメント</label>
            <div class="comment-content-area">
              <p><%= answer.comment %></p>
            </div>
              <%= "投稿日時 : " + answer.created_at.strftime('%Y/%m/%d') %><br>
              <%= answer.user.name %>
          <% end %>
        </div>
      </div>
      <div class="comment">
        <% if current_user == answer.user && answer.comment.present? && @question.status != "解決済" %>
        <%# <% binding.pry %>
          <div class="answer_edit">
            <button class="edit_answer_button"><%= link_to "回答編集", edit_question_answer_path(question, answer), remote: true %></button>
            <button><%= link_to "回答削除", question_answer_path(answer.question_id, answer.id), method: :delete, remote: true,
                                          data: { confirm: "本当に削除しますか?"} %></button>
          </div>
        <% end %>
      </div>
    </div>
  <% end %>
<% end %>

app/views/answers/create.html.erb
<h1>Answers#create</h1>
<p>Find me in app/views/answers/create.html.erb</p>

app/views/answers/edit.js.erb
$("#this_answer_<%= @answer.id %>").replaceWith("<%= j render 'answers/edit', question: @question, answer: @answer, answer_word: @answer_words %>");
$("#notice").html("<%= j flash[:notice] %>");

<%# // turbolinks:loadイベントを使用してページロード時にイベントハンドラーを設定 %>
<%# document.addEventListener('turbolinks:load', function() {
  document.querySelectorAll('.edit_answer_button').forEach(function(button) {
    button.addEventListener('click', function() {
      // 編集フォームのIDを取得して、そのフォームを非表示にする
      var formToHide = document.getElementById("answer_form_new");
      if (formToHide) {
        formToHide.style.display = 'none';
      }
    });
  });
}); %>
document.addEventListener('turbolinks:load', function() {
  console.log('ページがロードされました。イベントリスナーを設定中...');

  document.querySelectorAll('.edit_answer_button').forEach(function(button) {
    console.log('イベントリスナーを設定します: ', button);
    button.addEventListener('click', function() {
      console.log('ボタンがクリックされました。');
      var formToHide = document.getElementById("answer_form_new");
      if (formToHide) {
        console.log('フォームを非表示にします。');
        formToHide.style.display = 'none';
      } else {
        console.log('非表示にすべきフォームが見つかりません。');
      }
    });
  });
});

app/views/answers/index.js.erb
$("#answers_area").html("<%= j(render 'answers/index', { answers: @answer.question.answers, question: @answer.question }) %>");
$("textarea").val('');
$("input[type=text]").val('');
$("#notice").html("<%= j flash[:notice] %>");

app/views/answers/new.html.erb
<head>
  <%= stylesheet_link_tag 'answer_new', :media => "all" %>
</head>

<div class="main_content">
  <h1><%= @question.status %></h1>
  <div class="question">
    <div class="question-main">
      <div class="content">
        <label>質問内容</label>
        <p><%= @question.content %></p>
      </div>
      <div class="sentence">
        <label>前後の文脈</label>
        <p><%= @question.sentence %></p>
      </div>
    </div>
    <div class="question-sub">
      <div class="reminiscent-word">
        <% @question.reminiscent_words.each do |reminiscent_word| %>
          <label><%= reminiscent_word.keyword %></label>
        <% end %>
      </div>
    </div>
  </div>
  <h2>回答一覧</h2>
  <div class="divider"></div>
    <div class="answer-area">
      <!-- 投稿されたコメント一覧をブログの詳細ページに表示するためのrender -->
      <%= render partial: 'answers/index', locals: { answers: @answers, question: @question } %>
      <!-- コメント入力欄をブログの詳細ページに表示するためのrender -->
      <%# <%= render partial: 'answers/form', locals: { answer: @answer, question: @question } %>
      <% unless @question.answered_by?(current_user) %>
        <div id="answer_form_<%= @answer.id || 'new' %>" class="new_answer_form_wrapper">
          <%= render partial: 'answers/form', locals: { answer: @answer, question: @question } %>
        </div>
      <% end %>

    </div>
</div>