config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    passwords: 'users/passwords'
  }
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
    post 'users/guest_admin_sign_in', to: 'users/sessions#guest_admin_sign_in'
  end
  resources :users, only: [:show]
  resources :questions do
    resources :answers, only: [:new, :create, :edit, :destroy, :update]
  end
  resources :answer_words, only: [:update]
  root 'tops#top'
  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end
  get 'search', to: 'reminiscent_words_dictionaries#search'
  get 'result', to: 'questions#result'
  post 'questions/:id/answers/new', to: 'answers#create'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Remi-tan</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'header_footer', :media => "all" %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <nav class="navbar navbar-default">
          <p><%= link_to 'Remi-tan', root_path %></p>
          <ul>
            <% if user_signed_in? %>
              <li><%= link_to "質問一覧", questions_path %></li>
              <li><%= link_to "質問する", new_question_path %></li>
              <li><%= link_to "連想ワード検索", search_path %></li>
              <li><%= link_to "マイページ", user_path(current_user.id) %></li>
              <% if current_user.try(:admin?) %>
                <li><%= link_to "管理者画面", rails_admin_path %></li>
              <% end %>
              <li><%= link_to "ログアウト", destroy_user_session_path, method: :delete %></li>
            <% else %>
              <li><%= link_to "ログイン", new_user_session_path %></li>
              <li><%= link_to "ユーザー登録", new_user_registration_path %></li>
              <li><%= link_to 'トップページ', root_path %></li>
            <% end %>
          </ul>
      </nav>
    </header>
    <div class="main">
      <div class="alert-space">
        <% if notice %>
          <p class="alert alert-notice"><%= notice %></p>
        <% end %>
        <% if alert %>
          <p class="alert alert-error"><%= alert %></p>
        <% end %>
      </div>
      <%= yield %>
    </div>
    <footer>
      <div class="footer_area">
        <p>Copyright © 2021 Rem-tan</p>
      </div>
    </footer>
  </body>
</html>